Notes about work in progress

* Current issues/Next steps
** Add inventory items
** Edit inventory items
** Delete inventory items
** Refactor list views?

** History for inventory? [[From Sara][See Sara's requirements]]

** STARTED FieldNotes list page
Filters
** STARTED Site list page
- add counts of items
- fix filter
- move Filter header to same line as Sites

** WAITING Edit fieldnote
- Write some JS to get confirmation if the Site is going to be changed
when editing; for now, it's disabled
** How to create snippets like:
{% comment
{% if...
<!-- -->
** FieldNote contributors
** other stuff
Using an href="?site=4 reloads the current site using this as a query
string.



** Photos

** For Sara
How much validation to do for DOI links?

Approach	        Good for	            Downsides
Strict regex validation	Known DOI formats	    Not flexible for other domains
Custom URL validator	General-purpose checks	    No network call; fast & safe
Resolvable validator	Mission-critical accuracy   Slow, risky, potentially unsafe

Fieldnotes:
Adding a note is only done from a Site page and adds the site to the
note.
- Markdown? (more work!)
- PDF/docx uploads? (more work!)
- Is a user-inputted summary useful?
- Is it OK to assign a field note to a new site? At the moment the
widget is disabled, but we could write some JS to get confirmation.
- Do we want to be able to create new fieldnotes from the fieldnote list page?
- Contributors or Submittors
Simple list of people who have contributed/submitted FieldNotes;
Only used for FieldNote user field?


** DOI issues:
2. Invalid URL not caught Verify type="url" is in HTML; check
   client-side validators




* From Sara
Item  history: see berkeley site
Add documents: linked to inventory/sensor
Add notes, linked to each history record
Photos are linked to sites
Field notes linked to site; photo links?
No supplier: encode mfr/supplier in model number field

* Filtering
How to INPUT filter parameters?
** Down the road:
Make the default lookup vary by field type (icontains for text, exact
for dropdowns, etc.).

Use custom filter functions (e.g., for combining multiple values).

Support exact match filters by using lookup_type: "exact".

Allow select dropdowns for related models (e.g., a list of Site objects).

Add custom widgets like a range slider for numeric fields.

** STARTED How to do various filters: exact, contains, eq lt gt, date ranges?


* Add photos and link to sites
Explore photo docs in official docs
See also [[https://djangocentral.com/uploading-images-with-django/][overview]]
Where do photos get placed? Sites? Freestanding but with sites?
Where do photos get placed? In a single folder or in subfolders by site?




* STARTED maintenance records + new record on item edit/create template


* Add new site from inventory location dropdown

* eventually for missing inventory location:
check into listing unlocated items somewhere
automatically reassign them to a "Holding Area" or dummy location
instead of Null
See Highlight unassigned inventory items on Django Edit location tab

add to inventory templates to show NO location selected (can happen
ONLY if a location is deleted:

{{ item.location.name|default:"Not located" }}
OR
{% if item.location %}
  {{ item.location.name }}
{% else %}
  <span class="text-muted">Not located</span>
{% endif %}


* Unlocated items

* Conversations with Sara
** [2025-04-16 Wed]
Showed her the preliminary setup - locations mostly working, not
inventory w/maintenance records

Sara's site: https://github.com/CANFLUX/Biomet.net
Would like Photos, Field notes, Field Sites, Vendors/Suppliers? Models
See Denis' site for fields: https://biometlab.cnr.berkeley.edu/biometlab/bmetdata/equipment.php

She sent a spreadsheet with current material. See there for current
fields and values


* Next steps
** DEFERRED improve create/edit a location
map widget for address?
gps widget?
** DEFERRED fixtures!
how to dump and restore database

** write tests?
write TESTS for data models
** DEFERRED flesh out admin?
** DEFERRED flesh out userprofiles?


* TODOs
** Install Debug Toolbar
** Explore third-party ecosystem
   There's a 10-best list in LearnDjango.com site
   [[https://djangopackages.org/][Django Packages Org]]

** Hello, USER: set up a pull-down menu that includes:
   -logout
   -edit profile info

** Get current info for eventual importing
  [[https://ecoflux-lab.github.io/][Sara's lab site]]

** Customzie Admin Dashboard colours and header?


* Issues to sort
** authentication
*** DEFERRED Use custom user model from the start
    [[https://docs.djangoproject.com/en/5.1/topics/auth/customizing/#substituting-a-custom-user-model][See here]]
    Allows using email instead of username
*** using external authenticator like McGill's?
*** two-factor authentication?
** Database choice
   See Resources/Database selection and config

** Email backend for password resets
** static files
need set up in production?
** How to make the site bilingual



* Tests
** models
a. item
B. locations
C. maintenance record
For each possible permutation (A/B, A/C):
  create each object
  make associations between each pair of objects (a->b, b->a)
  delete each object; what is effect on the other? (ie need to make
    each pair once for each side of the deletion)


* Creds
hank ecoflux88



* Configuration
#+TODO: TODO(t) NEXTACTION(n) STARTED(s) WAITING(w) | DONE(d) CANCELED(c) DEFERRED(f)
