# Generated by Django 5.2.1 on 2025-05-21 21:27

import django.db.models.deletion
import inventory.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Site",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("code", models.CharField(max_length=10)),
                ("amp", models.CharField(max_length=10)),
                ("location", models.CharField(max_length=250)),
                ("description", models.TextField()),
                ("date_activated", models.DateField()),
                ("date_retired", models.DateField(blank=True, null=True)),
                ("gps_coordinates", models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="DOI",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=20)),
                ("doi_link", models.URLField()),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doi_records",
                        to="inventory.site",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SitePhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=inventory.models.site_photo_upload_path
                    ),
                ),
                ("caption", models.CharField(blank=True, max_length=255)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="inventory.site",
                    ),
                ),
            ],
        ),
    ]
