# Generated by Django 5.2.3 on 2025-08-02 09:59

import django.db.models.deletion
import django.utils.timezone
import inventory.models
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = []

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Site",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("code", models.CharField(max_length=10)),
                ("amp", models.CharField(max_length=10)),
                ("location", models.CharField(max_length=250)),
                ("description", models.TextField()),
                ("date_activated", models.DateField()),
                ("date_retired", models.DateField(blank=True, null=True)),
                ("gps_coordinates", models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="DOI",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=20)),
                ("doi_link", models.URLField()),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doi_records",
                        to="inventory.site",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FieldNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("note", models.TextField()),
                ("date_submitted", models.DateField(default=django.utils.timezone.now)),
                ("submitter", models.CharField()),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fieldnotes",
                        to="inventory.site",
                    ),
                ),
                ("summary", models.CharField(blank=True, max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name="Photo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=inventory.models.site_photo_upload_path
                    ),
                ),
                ("caption", models.CharField(blank=True, max_length=255)),
                ("uploaded_at", models.DateField(default=django.utils.timezone.now)),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="inventory.site",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Equipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("instrument", models.CharField(max_length=75)),
                ("manufacturer", models.CharField(blank=True, max_length=75)),
                ("model_number", models.CharField(blank=True, max_length=75)),
                ("serial_number", models.CharField(blank=True, max_length=50)),
                ("date_purchased", models.DateField()),
                ("notes", models.TextField(blank=True)),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="equipment",
                        to="inventory.site",
                    ),
                ),
            ],
        ),
    ]
