# Generated by Django 5.2.5 on 2025-08-13 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="equipment",
            old_name="location",
            new_name="site",
        ),
    ]
