# Generated by Django 5.2.5 on 2025-08-13 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_rename_location_equipment_site"),
    ]

    operations = [
        migrations.AddField(
            model_name="fieldnote",
            name="site_visitors",
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
