# Generated by Django 5.2.3 on 2025-08-03 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_history"),
    ]

    operations = [
        migrations.AddField(
            model_name="photo",
            name="submitter",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="fieldnote",
            name="submitter",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
