# Generated by Django 5.2.3 on 2025-08-03 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_photo_submitter_alter_fieldnote_submitter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="history",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="history",
                to="inventory.equipment",
            ),
        ),
    ]
