# Generated by Django 5.2.5 on 2025-08-13 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_fieldnote_site_visitors"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fieldnote",
            name="site_visitors",
            field=models.CharField(blank=True, default="", max_length=250),
        ),
    ]
