# Generated by Django 5.2.5 on 2025-08-19 01:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_alter_fieldnote_site_visitors"),
    ]

    operations = [
        migrations.RenameField(
            model_name="photo",
            old_name="image",
            new_name="photo",
        ),
        migrations.RemoveField(
            model_name="photo",
            name="uploaded_at",
        ),
        migrations.AddField(
            model_name="photo",
            name="date_taken",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="photo",
            name="date_uploaded",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="photo",
            name="taken_by",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
