# Generated by Django 5.2.5 on 2025-08-25 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "inventory",
            "0005_rename_image_photo_photo_remove_photo_uploaded_at_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="photo",
            name="caption",
        ),
        migrations.RemoveField(
            model_name="photo",
            name="date_uploaded",
        ),
        migrations.RemoveField(
            model_name="photo",
            name="site",
        ),
        migrations.RemoveField(
            model_name="photo",
            name="submitter",
        ),
        migrations.AddField(
            model_name="photo",
            name="fieldnote",
            field=models.ForeignKey(
                default=4,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="photos",
                to="inventory.fieldnote",
            ),
            preserve_default=False,
        ),
    ]
