# Generated by Django 5.2.5 on 2025-08-26 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0006_remove_photo_caption_remove_photo_date_uploaded_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="fieldnote",
            old_name="date_submitted",
            new_name="date_visited",
        ),
    ]
