# Generated by HK 2026-02-21 to
"""Reformat existing text in Fieldnote.note field from plain text to
HTML for TinyMCE text editing field."""

from django.db import migrations


def convert_to_html(apps, schema_editor):
    """Convert plain text formatted with spaces and punctuation to HTML:

    Convert \n to <br>.
    Lines ending wihout a period (but not ending with a URL backslash)
    -> <strong>
    Lines starting with - or * -> <li> in an <ul> block with
    appropriate nesting.
    Line segments with a colon, up to the colon -> <strong>
    """

    list_labels = ("-", "*")

    YourModel = apps.get_model("inventory", "FieldNote")
    for obj in YourModel.objects.all():
        punctuation = obj.note.find(".") > -1
        converted_text = []
        list_stack = []
        in_list = False
        note = obj.note.replace("\n", "<br>")

        for line in [ln.strip() for ln in note.split("<br>")]:
            if line.startswith(list_labels):
                # Deal with list items
                li_label = line[0]
                try:
                    index = list_stack.index(li_label)
                    list_stack_len = len(list_stack)

                    if list_stack_len - index == 1:
                        # We're continuing an existing list, no need
                        # to prepend anything.
                        prepend = ""
                    else:
                        # We're moving backwards to a previous list,
                        # prepent </ul>(s) to line
                        prepend = ""
                        for n in range(list_stack_len - index - 1):
                            prepend += "</ul>"
                            list_stack.pop()

                except:
                    # This is the first time we've seen this list label.
                    list_stack.append(li_label)
                    prepend = "<ul>"
                    in_list = True

                line = f"{prepend}<li>{line[1:].strip()}</li>"
            else:
                # Non-list items
                if in_list:
                    # Close all pending lists.
                    prepend = ""
                    for n in range(len(list_stack)):
                        prepend += "</ul>"
                    in_list = False
                    list_stack = []
                else:
                    prepend = ""
                if line and punctuation and not line.endswith((".", "/")):
                    line = f"{prepend}<strong>{line}</strong>"
                else:
                    # Highlight text before a colon
                    colon_index = line.find(":")
                    # Try to avoid timestamps and https://
                    if (
                        colon_index > -1
                        and not line[colon_index - 1].isdigit()
                        and line.find("http") < 0
                    ):
                        line = f"{prepend}<strong>{line[:colon_index + 1]}</strong>{line[colon_index + 1:]}"
                    else:
                        line = f"{prepend}{line}"
                line += "<br>"
            converted_text.append(line)

        obj.note = "".join(converted_text)
        obj.save()


def reverse_conversion(apps, schema_editor):
    """This method is a NoOp since this migration is only meant to be
    run once and only on the production server."""

    pass


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0007_rename_date_submitted_fieldnote_date_visited"),
    ]

    operations = [
        migrations.RunPython(convert_to_html, reverse_conversion),
    ]
