# Generated by Django 6.0.3 on 2026-04-09 02:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("inventory", "0008_fieldnote_text_2_html"),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                ("date_uploaded", models.DateField(default=django.utils.timezone.now)),
                ("submitter", models.CharField(blank=True, max_length=50, null=True)),
                ("date_received", models.DateField()),
                ("summary", models.CharField(max_length=80)),
                (
                    "file",
                    models.FileField(upload_to="documents/", verbose_name="document"),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="inventory_d_content_079867_idx",
                    )
                ],
            },
        ),
    ]
