# Generated by Django 6.0.3 on 2026-04-11 15:24

import inventory.media_processing.media_paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0009_document"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="thumbnail",
            field=models.ImageField(
                blank=True, null=True, upload_to="thumbnails/documents"
            ),
        ),
        migrations.AddField(
            model_name="photo",
            name="thumbnail",
            field=models.ImageField(
                blank=True, null=True, upload_to="thumbnails/images/"
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="file",
            field=models.FileField(
                upload_to=inventory.media_processing.media_paths.document_upload_path,
                verbose_name="document",
            ),
        ),
    ]
