# Generated by Django 6.0.3 on 2026-04-11 21:54

import inventory.media_processing.media_paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0010_document_thumbnail_photo_thumbnail_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=inventory.media_processing.media_paths.document_thumbnail_upload_path,
                verbose_name="thumbnail",
            ),
        ),
        migrations.AlterField(
            model_name="photo",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=inventory.media_processing.media_paths.image_thumbnail_upload_path,
                verbose_name="thumbnail",
            ),
        ),
    ]
