# Generated by Django 6.0.3 on 2026-04-15 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0011_alter_document_thumbnail_alter_photo_thumbnail"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="object_description",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
