# --------------------------
# WSGI Daemon Processes
# --------------------------
WSGIDaemonProcess testing_ecoflux python-home=/srv/testing_ecoflux/.venv python-path=/srv/testing_ecoflux
WSGIDaemonProcess ecoflux python-home=/srv/ecoflux/.venv python-path=/srv/ecoflux

# Main HTTPS VirtualHost
<VirtualHost *:443>
    ServerName grandwazoo.ddns.net
    ServerAlias grandwazoo.ddns.net
    ServerAdmin hank.knox@mcgill.ca

    # --------------------------
    # SSL
    # --------------------------
    SSLEngine on
    SSLCertificateFile /etc/ssl/nextcloud/grandwazoo_ddns_net.crt
    SSLCertificateKeyFile /etc/ssl/nextcloud/grandwazoo.ddns.net.key
    SSLCertificateChainFile /etc/ssl/nextcloud/DigiCertCA.crt

    # --------------------------
    # NEXTCLOUD at /
    # --------------------------
    Header always set Strict-Transport-Security "max-age=15552000"
    DocumentRoot /var/www/html/nextcloud

    <Directory /var/www/html/nextcloud/>
        Options Indexes FollowSymLinks MultiViews
        AllowOverride All
        Require all granted
        DirectoryIndex index.php index.html
        <IfModule mod_dav.c>
            Dav off
        </IfModule>
    </Directory>

    # --------------------------
    # ECOFLUX at /ecoflux/ - Django production app
    # --------------------------
    # Adjust python-path for your Python version & venv location
    WSGIScriptAlias /ecoflux /srv/ecoflux/EcoFlux/wsgi-production.py process-group=ecoflux
    # WSGIApplicationGroup %{GLOBAL}

    <Directory /srv/ecoflux/EcoFlux>
        <Files wsgi-production.py>
            Require all granted
        </Files>
    </Directory>

    # Static files for production
    Alias /ecoflux/static/ /srv/ecoflux/staticfiles/
    <Directory /srv/ecoflux/staticfiles/>
      Require all granted
        <FilesMatch "\.(js|css|png|gif|ico|jpg|jpeg|svg|woff|woff2|ttf|eot)$">
	  Header set Cache-Control "public, max-age=31536000, immutable"
	</FilesMatch>
    </Directory>

    # Media files for production
    Alias /ecoflux/media/ /srv/ecoflux/media/
    <Directory /srv/ecoflux/media/>
       Require all granted
    </Directory>

    # wsgi-production.py stanza is enough?
    # <Directory /srv/ecoflux/EcoFlux>
    #    Require all granted
    # </Directory>


    # --------------------------
    # TESTING_ECOFLUX at /testing_ecoflux/
    # --------------------------
    # Adjust python-path for your Python version & venv location
    WSGIScriptAlias /testing_ecoflux /srv/testing_ecoflux/EcoFlux/wsgi-production.py process-group=testing_ecoflux

    <Directory /srv/testing_ecoflux/EcoFlux>
        <Files wsgi-production.py>
            Require all granted
        </Files>
    </Directory>

    # Static files for testing
    Alias /testing_ecoflux/static/ /srv/testing_ecoflux/staticfiles/
    <Directory /srv/testing_ecoflux/staticfiles/>
      Require all granted
        <FilesMatch "\.(js|css|png|gif|ico|jpg|jpeg|svg|woff|woff2|ttf|eot)$">
	  Header set Cache-Control "public, max-age=31536000, immutable"
	</FilesMatch>
    </Directory>

    # Media files for testing
    Alias /testing_ecoflux/media/ /srv/testing_ecoflux/media/
    <Directory /srv/testing_ecoflux/media/>
       Require all granted
    </Directory>

    # wsgi-production.py stanza is enough?
    # <Directory /srv/testing_ecoflux/EcoFlux>
    #    Require all granted
    # </Directory>


    # --------------------------
    # MAKE SURE THESE ARE ALWAYS ENABLED!
    # --------------------------
    # Logs
    # --------------------------
    ErrorLog ${APACHE_LOG_DIR}/grandwazoo-error.log
    CustomLog ${APACHE_LOG_DIR}/grandwazoo-access.log combined


</VirtualHost>

# HTTP -> HTTPS redirect
<VirtualHost *:80>
    ServerName grandwazoo.ddns.net
    ServerAlias grandwazoo.ddns.net
    Redirect permanent / https://grandwazoo.ddns.net/
</VirtualHost>
