"""Django settings for EcoFlux project common to development and
production environments.

Generated by 'django-admin startproject' using Django 5.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/

See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

"""

from pathlib import Path
from decouple import config, Csv
import os.path
import subprocess

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

IN_PRODUCTION = config("IN_PRODUCTION", False, cast=bool)
VERSION_FILE = os.path.join(BASE_DIR, "VERSION")
if IN_PRODUCTION:
    try:
        with open(VERSION_FILE) as f:
            GIT_VERSION = f.read().strip()
    except FileNotFoundError:
        GIT_VERSION = "unknown"
else:
    result = subprocess.run(
        ["git", "describe", "--tags", "--always", "--dirty"],
        cwd=BASE_DIR,
        capture_output=True,
        text=True,
    )
    GIT_VERSION = result.stdout.strip() or "unknown"

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DEBUG", False, cast=bool)

ADMINS = config("ADMINS", default="", cast=Csv())

ALLOWED_HOSTS = config("ALLOWED_HOSTS", default=[], cast=Csv())
# These are only appropriate when serving via proxy. If the server is
# not behind a proxy, these variables might not be defined in .env.
try:
    CORS_ALLOWED_ORIGINS = config("CORS_ALLOWED_ORIGINS", default=[], cast=Csv())
except AttributeError:
    CORS_ALLOWED_ORIGINS = []
try:
    CSRF_TRUSTED_ORIGINS = config("CSRF_TRUSTED_ORIGINS", default=[], cast=Csv())
except AttributeError:
    CSRF_TRUSTED_ORIGINS = []

# Application definition
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.admindocs",
    "django.contrib.staticfiles",
    "django_bootstrap5",
    "maintenance_mode",
    "inventory",
    "corsheaders",
    "crispy_forms",
    "crispy_bootstrap5",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",  # must come before local Middleware
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "maintenance_mode.middleware.MaintenanceModeMiddleware",
    "middleware.NavigationHistoryMiddleware",  # after session middleware
]

ROOT_URLCONF = "EcoFlux.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
            "builtins": ["django.templatetags.static"],
        },
    },
]

WSGI_APPLICATION = "EcoFlux.wsgi.application"

DATABASES = {
    "default": {
        "ENGINE": config("DB_ENGINE"),
        "NAME": config("DB_NAME", default=""),
        "USER": config("DB_USER", default=""),
        "PASSWORD": config("DB_PASSWORD", default=""),
        "HOST": config("DB_HOST", default=""),
        "PORT": config("DB_PORT", default=""),
    },
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True

MESSAGE_STORAGE = "django.contrib.messages.storage.session.SessionStorage"


# STATIC FILES (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6,0/howto/static-files/

# URL to use when referring to static files located in STATIC_ROOT. If
# not None, this will be used as the base path for asset definitions
# (the Media class) and the staticfiles app. It must end in a slash if
# set to a non-empty value
STATIC_URL = config("STATIC_URL", "static/")
# This setting defines the additional locations the staticfiles app
# will traverse if the FileSystemFinder finder is enabled, e.g. if you
# use the collectstatic or findstatic management command or use the
# static file serving view. it should be set to a list of strings
# that contain full paths to your additional files directory(ies).
STATICFILES_DIRS = (BASE_DIR / "static",)
# The absolute path to the directory where collectstatic will collect
# static files for deployment:
STATIC_ROOT = BASE_DIR / "staticfiles"
# STATICFILES_FINDERS
# Default:
# [
#     "django.contrib.staticfiles.finders.FileSystemFinder",
#     "django.contrib.staticfiles.finders.AppDirectoriesFinder",
# ]
# The list of finder backends that know how to find static files in
# various locations.

# The default will find files stored in the STATICFILES_DIRS setting
# (using django.contrib.staticfiles.finders.FileSystemFinder) and in a
# static subdirectory of each app (using
# django.contrib.staticfiles.finders.AppDirectoriesFinder). If
# multiple files with the same name are present, the first file that
# is found will be used.

# One finder is disabled by default:
# django.contrib.staticfiles.finders.DefaultStorageFinder. If added to
# your STATICFILES_FINDERS setting, it will look for static files in
# the default file storage as defined by the default key in the
# STORAGES setting. Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Account Management
LOGIN_URL = config("LOGIN_URL", "/accounts/login")
LOGIN_REDIRECT_URL = "home"
LOGOUT_REDIRECT_URL = "home"
# EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = config("EMAIL_HOST", default="localhost")
EMAIL_PORT = config("EMAIL_PORT", default=25, cast=int)
EMAIL_HOST_USER = config("EMAIL_HOST_USER", default="")
EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD", default="")
EMAIL_USE_SSL = config("EMAIL_USE_SSL", default=False, cast=bool)

SESSION_COOKIE_AGE = 259200  # 3 days

# Media uploads
MEDIA_URL = config("MEDIA_URL", default="/media/")
MEDIA_ROOT = BASE_DIR / "media"
PHOTO_UPLOAD_SUBDIR = "site_photos/"
DOCUMENT_UPLOAD_SUBDIR = "documents/"
MEDIA_THUMBNAIL_SUBDIR = "thumbnails/"
DEFAULT_FILE_STORAGE = "django.core.files.storage.FileSystemStorage"

# crispy-forms
CRISPY_ALLOWED_TEMPLATE_PACKS = ("bootstrap5",)
CRISPY_TEMPLATE_PACK = "bootstrap5"
CRISPY_FAIL_SILENTLY = not DEBUG

DJANGO_SETTINGS_MODULE = config("DJANGO_SETTINGS_MODULE")

# Logging
LOG_DIR = os.path.join(BASE_DIR, "logs")

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "with_datetime": {
            "format": "{asctime} {message}",
            "style": "{",
            "datefmt": "%Y-%m-%d %H:%M:%S",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "with_datetime",
        },
        "file": {
            "class": "logging.handlers.RotatingFileHandler",
            "filename": os.path.join(LOG_DIR, "django_logs.log"),
            "maxBytes": 1024 * 1024 * 100,
            "backupCount": 9,
            "formatter": "with_datetime",
        },
    },
    "loggers": {
        "inventory": {  # Use the name of your app's logger
            "handlers": ["console", "file"],
            "level": "INFO",
            "propagate": False,
        },
        "django": {
            "handlers": ["console", "file"],
            "level": "WARN",
            "propagate": False,
        },
    },
    # Fallback logger
    "root": {
        "handlers": ["console", "file"],
        "level": "INFO",
    },
}

# MAINTENANCE mode variables, see
# https://github.com/fabiocaccamo/django-maintenance-mode
MAINTENANCE_MODE = config("MAINTENANCE_MODE", default=False, cast=bool)
MAINTENANCE_MODE_LOGOUT_AUTHENTICATED_USER = config(
    "MAINTENANCE_LOGOUT", default=False, cast=bool
)
MAINTENANCE_MODE_IGNORE_SUPERUSER = config(
    "MAINTENANCE_MODE_IGNORE_SUPERUSER", default=False, cast=bool
)
MAINTENANCE_MODE_GET_CONTEXT = "inventory.maintenance_testing.get_context_data"
MAINTENANCE_MODE_TEMPLATE = "inventory/under_construction.html"
